import PDFDocument from 'pdfkit';
import { createObjectCsvStringifier } from 'csv-writer';
import Transaction from '../models/Transaction.js';
import Contact from '../models/Contact.js';
import { PAISE_PER_INR } from '../utils/constants.js';

const generatePDF = async (userId, contactId, fromDate, toDate) => {
  const doc = new PDFDocument({ margin: 50 });
  const buffers = [];

  doc.on('data', (chunk) => buffers.push(chunk));

  return new Promise((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    const filter = { owner: userId };
    if (contactId) filter.contact = contactId;

    Transaction.find(filter)
      .populate('contact', 'name phone')
      .sort({ date: -1 })
      .lean()
      .then((transactions) => {
        doc.fontSize(20).font('Helvetica-Bold').text('Udhar Khata', { align: 'center' });
        doc.fontSize(10).font('Helvetica').text('Your Personal Loan Ledger', { align: 'center' });
        doc.moveDown();

        doc.fontSize(12).font('Helvetica-Bold').text('Export Summary', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(10).font('Helvetica');

        if (fromDate) doc.text(`From: ${new Date(fromDate).toLocaleDateString('en-IN')}`);
        if (toDate) doc.text(`To: ${new Date(toDate).toLocaleDateString('en-IN')}`);
        doc.text(`Total Transactions: ${transactions.length}`);
        doc.moveDown();

        const contactTotals = {};

        transactions.forEach((t) => {
          const cName = t.contact?.name || 'Unknown';
          if (!contactTotals[cName]) {
            contactTotals[cName] = { gave: 0, received: 0, transactions: [] };
          }
          contactTotals[cName].transactions.push(t);
          if (t.type === 'gave') contactTotals[cName].gave += t.amount;
          else contactTotals[cName].received += t.amount;
        });

        Object.entries(contactTotals).forEach(([name, data]) => {
          if (doc.y > 600) {
            doc.addPage();
          }

          doc.fontSize(12).font('Helvetica-Bold').fillColor('#1a1a1a').text(name);
          doc.moveDown(0.3);

          doc.fontSize(8).font('Helvetica-Bold').fillColor('#666');
          doc.text(
            'Date'.padEnd(14) + 'Type'.padEnd(10) + 'Amount'.padEnd(12) + 'Category'.padEnd(12) + 'Note',
            { width: 500 }
          );
          doc.fontSize(8).font('Helvetica').fillColor('#333');

          data.transactions.forEach((t) => {
            const date = new Date(t.date).toLocaleDateString('en-IN');
            const type = t.type === 'gave' ? 'Gave' : 'Received';
            const amt = `₹${(t.amount / PAISE_PER_INR).toLocaleString('en-IN')}`;
            doc.text(
              date.padEnd(14) + type.padEnd(10) + amt.padEnd(12) + (t.categoryTag || '').padEnd(12) + (t.note || ''),
              { width: 500 }
            );
          });

          doc.moveDown(0.3);
          const netAmt = (data.gave - data.received) / PAISE_PER_INR;
          doc.font('Helvetica-Bold').fillColor(netAmt >= 0 ? '#16a34a' : '#dc2626');
          doc.text(`Net: ₹${Math.abs(netAmt).toLocaleString('en-IN')} (${netAmt >= 0 ? 'You gave' : 'You received'})`);
          doc.moveDown(0.8);
        });

        doc.moveDown();
        doc.fontSize(14).font('Helvetica-Bold').fillColor('#1a1a1a').text('Overall Summary');
        doc.moveDown(0.5);

        let totalGave = 0;
        let totalReceived = 0;
        transactions.forEach((t) => {
          if (t.type === 'gave') totalGave += t.amount;
          else totalReceived += t.amount;
        });

        const overallNet = (totalGave - totalReceived) / PAISE_PER_INR;
        doc.fontSize(10).font('Helvetica');
        doc.text(`Total Given: ₹${(totalGave / PAISE_PER_INR).toLocaleString('en-IN')}`);
        doc.text(`Total Received: ₹${(totalReceived / PAISE_PER_INR).toLocaleString('en-IN')}`);
        doc.font('Helvetica-Bold');
        doc.text(
          `Net Balance: ₹${Math.abs(overallNet).toLocaleString('en-IN')} (${overallNet >= 0 ? 'Others owe you' : 'You owe others'})`
        );

        doc.moveDown(2);
        doc.fontSize(8).font('Helvetica').fillColor('#999');
        doc.text('Generated by Udhar Khata', { align: 'center' });
        doc.text(`Generated on: ${new Date().toLocaleString('en-IN')}`, { align: 'center' });

        doc.end();
      })
      .catch(reject);
  });
};

const generateCSV = async (userId, contactId, fromDate, toDate) => {
  const filter = { owner: userId };
  if (contactId) filter.contact = contactId;
  if (fromDate || toDate) {
    filter.date = {};
    if (fromDate) filter.date.$gte = new Date(fromDate);
    if (toDate) filter.date.$lte = new Date(toDate);
  }

  const transactions = await Transaction.find(filter)
    .populate('contact', 'name')
    .sort({ date: -1 })
    .lean();

  const csvStringifier = createObjectCsvStringifier({
    header: [
      { id: 'date', title: 'Date' },
      { id: 'contact', title: 'Contact' },
      { id: 'type', title: 'Type' },
      { id: 'amount', title: 'Amount (INR)' },
      { id: 'note', title: 'Note' },
      { id: 'category', title: 'Category' },
      { id: 'settled', title: 'Settled' },
      { id: 'dueDate', title: 'Due Date' },
    ],
  });

  const records = transactions.map((t) => ({
    date: new Date(t.date).toLocaleDateString('en-IN'),
    contact: t.contact?.name || 'Unknown',
    type: t.type === 'gave' ? 'Gave' : 'Received',
    amount: (t.amount / PAISE_PER_INR).toFixed(2),
    note: t.note || '',
    category: t.categoryTag || '',
    settled: t.isSettled ? 'Yes' : 'No',
    dueDate: t.dueDate ? new Date(t.dueDate).toLocaleDateString('en-IN') : '',
  }));

  const header = csvStringifier.getHeaderString();
  const body = csvStringifier.stringifyRecords(records);

  return header + body;
};

export { generatePDF, generateCSV };
